CREATE TABLE IF NOT EXISTS bookings (
  id VARCHAR(40) PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(32) NOT NULL DEFAULT 'new',
  festival VARCHAR(255) NOT NULL,
  plan VARCHAR(255) NOT NULL,
  retail_rate VARCHAR(255) NOT NULL,
  arrival_date DATE NULL,
  nights INT NOT NULL,
  guests INT NOT NULL,
  food VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(64) NOT NULL,
  notes TEXT NULL,
  source VARCHAR(64) NOT NULL DEFAULT 'website'
);

CREATE TABLE IF NOT EXISTS enquiries (
  id VARCHAR(40) PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(32) NOT NULL DEFAULT 'new',
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(64) NULL,
  email VARCHAR(255) NULL,
  subject VARCHAR(255) NULL,
  message TEXT NOT NULL,
  source VARCHAR(64) NOT NULL DEFAULT 'website'
);
