const whatsappNumber = "918719962147";
const cafeMenu = [["Fried rice", [["Veg fried rice",180],["Chicken fried rice",230],["Pork fried rice",250],["Mix fried rice",270],["Schezwan fried rice",230]]],["Chowmein", [["Veg chowmein",170],["Chicken chowmein",220],["Pork chowmein",240],["Schezwan chowmein",210],["Mix chowmein",250]]],["Rolls & momos", [["Veg roll",100],["Egg roll",120],["Chicken roll",150],["Pork roll",160],["Veg momo",140],["Chicken momo",180],["Pork momo",200],["Fried momo",200]]],["Snacks & sides", [["French fries",120],["Peri peri fries",150],["Veg pakoda",120],["Paneer pakoda",180],["Chicken 65",260],["Chilli chicken dry",260],["Grilled chicken",320],["Pork dry fry",340]]],["Mains", [["Chicken manchurian",260],["Chilli chicken gravy",260],["Hot garlic chicken gravy",270],["Chicken butter masala",300],["Veg combo",260],["Chicken or pork combo",320],["Plain dosa",120],["Masala dosa",160]]],["Beverages", [["Red Bull",300],["Coke",80],["Pepsi",80],["Sprite",80],["Water bottle 500 ml",20]]]];
const barMenu = [["30 ml pours", [["Jameson — 30 ml",300],["Jamun — 30 ml",200],["Bacardi Limon — 30 ml",200],["Blenders Blue — 30 ml",200],["100 Pipers — 30 ml",250],["Bacardi Plain — 30 ml",200],["Jose Cuervo Silver — 30 ml",500],["Jägermeister — 30 ml",500]]],["60 ml pours", [["Jameson — 60 ml",600],["Jamun — 60 ml",400],["Bacardi Limon — 60 ml",400],["Blenders Blue — 60 ml",400],["100 Pipers — 60 ml",500],["Bacardi Plain — 60 ml",400],["Jose Cuervo Silver — 60 ml",1000],["Jägermeister — 60 ml",1000]]],["Bottles", [["Jameson bottle",7000],["Jamun bottle",4500],["Bacardi Limon bottle",4500],["Blenders Blue bottle",4500],["100 Pipers bottle",5700],["Bacardi Plain bottle",4500]]],["Beer & mixers", [["Budweiser Premium can",300],["Kingfisher Ultra can",250],["Red Bull",300],["Water bottle 500 ml",20]]]];
const page = document.body.dataset.menuKind, menu = page === "bar" ? barMenu : cafeMenu;
const storageKey = `nbc-${page}-cart`, guestStorageKey = `nbc-${page}-guest`, historyStorageKey = `nbc-${page}-order-history`;
let cart = JSON.parse(localStorage.getItem(storageKey) || "[]"), guest = JSON.parse(localStorage.getItem(guestStorageKey) || "{}"), history = JSON.parse(localStorage.getItem(historyStorageKey) || "[]");
const menuRoot = document.querySelector("#menuCategories"), cartRoot = document.querySelector("#cartItems"), totalRoot = document.querySelector("#cartTotal"), shareButton = document.querySelector("#shareOrder"), nameInput = document.querySelector("#guestName"), tentInput = document.querySelector("#guestTent"), formMessage = document.querySelector("#formMessage"), historyRoot = document.querySelector("#orderHistory"), historyCount = document.querySelector("#orderHistoryCount");
const money = amount => `₹${new Intl.NumberFormat("en-IN").format(amount)}`, productId = name => name.toLowerCase().replace(/[^a-z0-9]+/g, "-"), allProducts = menu.flatMap(([, items]) => items.map(([name, price]) => ({ id: productId(name), name, price }))), title = page === "bar" ? "Northeast Basecamp Bar" : "Northeast Basecamp Café";
nameInput.value = guest.name || ""; tentInput.value = guest.tent || "";
const saveCart = () => localStorage.setItem(storageKey, JSON.stringify(cart));
const saveGuest = () => { guest = { name: nameInput.value.trim(), tent: tentInput.value.trim() }; localStorage.setItem(guestStorageKey, JSON.stringify(guest)); };
const totalAmount = () => cart.reduce((sum, item) => sum + item.price * item.quantity, 0);
function showMessage(message, tone = "") { formMessage.textContent = message; formMessage.className = `form-message ${tone}`; }
function addItem(id, button) { const existing = cart.find(item => item.id === id); if (existing) existing.quantity += 1; else cart.push({ ...allProducts.find(item => item.id === id), quantity: 1 }); saveCart(); renderCart(); const item = cart.find(entry => entry.id === id), product = allProducts.find(entry => entry.id === id); showMessage(`${product.name} added — quantity ${item.quantity}.`, "success"); if (button) { const label = button.textContent; button.textContent = "Added 1"; button.classList.add("was-added"); setTimeout(() => { button.textContent = label; button.classList.remove("was-added"); }, 1100); } }
function changeQuantity(id, delta) { const item = cart.find(entry => entry.id === id); if (!item) return; item.quantity += delta; if (item.quantity <= 0) cart = cart.filter(entry => entry.id !== id); saveCart(); renderCart(); }
function renderMenu() { menuRoot.innerHTML = menu.map(([category, items]) => `<section class="menu-category"><h2>${category}</h2><div class="menu-items">${items.map(([name, price]) => `<article class="menu-item"><div><strong>${name}</strong><small>${page === "bar" ? "Basecamp bar price" : "Basecamp café price"}</small></div><div><span class="menu-price">${money(price)}</span><button class="add-item" type="button" data-add="${productId(name)}" aria-label="Add ${name} to cart">Add</button></div></article>`).join("")}</div></section>`).join(""); }
function renderCart() { cartRoot.innerHTML = cart.length ? cart.map(item => `<div class="cart-row"><div><strong>${item.name}</strong><span>${money(item.price)} each</span></div><div class="quantity"><button type="button" data-change="${item.id}" data-delta="-1">−</button><b>${item.quantity}</b><button type="button" data-change="${item.id}" data-delta="1">+</button></div><strong>${money(item.price * item.quantity)}</strong></div>`).join("") : '<p class="cart-empty">Your cart is empty. Add items to start an order.</p>'; totalRoot.textContent = money(totalAmount()); shareButton.disabled = !cart.length; }
function renderHistory() { historyCount.textContent = history.length; historyRoot.innerHTML = history.length ? history.slice(0, 5).map(order => `<div class="history-row"><strong>${order.name}</strong><span>${order.itemCount} item${order.itemCount === 1 ? "" : "s"} · ${money(order.total)}</span><small>${order.tent ? `Tent/table: ${order.tent} · ` : ""}${new Date(order.savedAt).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })}</small></div>`).join("") : '<p class="cart-empty">No saved drafts yet.</p>'; }
function shareOrder() { saveGuest(); if (!guest.name) { showMessage("Please add your name before sharing the order.", "error"); nameInput.focus(); return; } if (!cart.length) return; const total = totalAmount(), lines = cart.map(item => `• ${item.name} × ${item.quantity} — ${money(item.price * item.quantity)}`), itemCount = cart.reduce((count, item) => count + item.quantity, 0); history = [{ name: guest.name, tent: guest.tent, total, itemCount, savedAt: new Date().toISOString(), items: cart }, ...history].slice(0, 10); localStorage.setItem(historyStorageKey, JSON.stringify(history)); renderHistory(); const location = guest.tent ? `Tent / table: ${guest.tent}` : "Tent / table: Not provided"; const message = encodeURIComponent(`Hello ${title} team 👋\n\nI would like to place an order from Northeast Basecamp.\n\nGuest name: ${guest.name}\n${location}\n\nOrder details:\n${lines.join("\n")}\n\nFinal bill: ${money(total)}\n\nPlease confirm availability and delivery time. Thank you!\n\nAfter my order, please share how I can leave a review for Northeast Basecamp Café. We would love to hear about my experience. ⭐`); window.open(`https://wa.me/${whatsappNumber}?text=${message}`, "_blank", "noopener"); }
renderMenu(); renderCart(); renderHistory();
menuRoot.addEventListener("click", event => { const button = event.target.closest("[data-add]"); if (button) addItem(button.dataset.add, button); }); cartRoot.addEventListener("click", event => { const button = event.target.closest("[data-change]"); if (button) changeQuantity(button.dataset.change, Number(button.dataset.delta)); }); [nameInput, tentInput].forEach(input => input.addEventListener("input", saveGuest)); shareButton.addEventListener("click", shareOrder); document.querySelector("#clearCart").addEventListener("click", () => { cart = []; saveCart(); renderCart(); showMessage("Cart cleared. Your guest details remain saved."); });
